- hosts: localhost
  user: vagrant
  sudo: yes
  vars:
    db_name: testdb1
    db_user: root
    db_password: 123456
  tasks:
    - include: tasks/common.yml
    - include: tasks/nginx.yml
    - include: tasks/hhvm.yml
    - include: tasks/php.yml
    - include: tasks/composer.yml
    #- include: tasks/laravel.yml
    - include: tasks/mysql.yml
    - include: tasks/redis.yml
    - include: tasks/node.yml
